//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDepth.Module.WinService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDepth.Module.WinService.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot allocate console!.
        /// </summary>
        internal static string AllocateConsoleFailed {
            get {
                return ResourceManager.GetString("AllocateConsoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot free console!.
        /// </summary>
        internal static string FreeConsoleFailed {
            get {
                return ResourceManager.GetString("FreeConsoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to service control manager!.
        /// </summary>
        internal static string OpenSCManagerFailed {
            get {
                return ResourceManager.GetString("OpenSCManagerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse module configuration -{0}!.
        /// </summary>
        internal static string ParseModuleConfigFailed {
            get {
                return ResourceManager.GetString("ParseModuleConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to query service status!.
        /// </summary>
        internal static string QueryServiceStatusFailed {
            get {
                return ResourceManager.GetString("QueryServiceStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install service &apos;{0}&apos; - {1}!.
        /// </summary>
        internal static string ServiceCreateFailed {
            get {
                return ResourceManager.GetString("ServiceCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete service &apos;{0}&apos;! Error code: {1}..
        /// </summary>
        internal static string ServiceDeleteFailed {
            get {
                return ResourceManager.GetString("ServiceDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not installed &apos;{0}&apos;!.
        /// </summary>
        internal static string ServiceNotInstalled {
            get {
                return ResourceManager.GetString("ServiceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open service &apos;{0}&apos;!.
        /// </summary>
        internal static string ServiceOpenFailed {
            get {
                return ResourceManager.GetString("ServiceOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started! Press Enter to stop..
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start service!.
        /// </summary>
        internal static string ServiceStartFailed {
            get {
                return ResourceManager.GetString("ServiceStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is starting....
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to stop service!.
        /// </summary>
        internal static string ServiceStopFailed {
            get {
                return ResourceManager.GetString("ServiceStopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stopped!.
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is stopping....
        /// </summary>
        internal static string ServiceStopping {
            get {
                return ResourceManager.GetString("ServiceStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [-help | /help | -? | /?]  --- Show this help.
        /// </summary>
        internal static string UsageMessage1 {
            get {
                return ResourceManager.GetString("UsageMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [-install | /install]      --- Install Windows Service.
        /// </summary>
        internal static string UsageMessage2 {
            get {
                return ResourceManager.GetString("UsageMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [-uninstall | /uninstall]  --- Uninstall Windows Service.
        /// </summary>
        internal static string UsageMessage3 {
            get {
                return ResourceManager.GetString("UsageMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [-start | /start]          --- Start Windows Service.
        /// </summary>
        internal static string UsageMessage4 {
            get {
                return ResourceManager.GetString("UsageMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [-stop | /stop]            --- Stop Windows Service.
        /// </summary>
        internal static string UsageMessage5 {
            get {
                return ResourceManager.GetString("UsageMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [-console | /console]      --- Run Windows Service in console mode.
        /// </summary>
        internal static string UsageMessage6 {
            get {
                return ResourceManager.GetString("UsageMessage6", resourceCulture);
            }
        }
    }
}
