//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDepth.Configuration.ConfigurationManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDepth.Configuration.ConfigurationManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration manager is not initialized!.
        /// </summary>
        internal static string ConfigurationManagerNotInitialized {
            get {
                return ResourceManager.GetString("ConfigurationManagerNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata configuration cannot be performed after initialization of the configuration manager!.
        /// </summary>
        internal static string MetaDataConfigAfterInitializiation {
            get {
                return ResourceManager.GetString("MetaDataConfigAfterInitializiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata configuration already contains entity with the diven name - {0}.
        /// </summary>
        internal static string MetaDataConfigDuplicateByName {
            get {
                return ResourceManager.GetString("MetaDataConfigDuplicateByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata configuration already contains entity with the diven type - {0}.
        /// </summary>
        internal static string MetaDataConfigDuplicateByType {
            get {
                return ResourceManager.GetString("MetaDataConfigDuplicateByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader lock should be held to perform the operation with the configuration manager!.
        /// </summary>
        internal static string ReaderLockNotHeld {
            get {
                return ResourceManager.GetString("ReaderLockNotHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer lock should be held to perform the operation with the configuration manager!.
        /// </summary>
        internal static string WriterLockNotHeld {
            get {
                return ResourceManager.GetString("WriterLockNotHeld", resourceCulture);
            }
        }
    }
}
